In [63]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

In [64]:
df=pd.read_csv('train_dataset.csv',index_col='ID')
df1=pd.read_csv('test_dataset.csv',index_col='ID')
print(df.columns, df1.columns)

Index(['N_Days', 'Status', 'Drug', 'Age', 'Sex', 'Ascites', 'Hepatomegaly',
       'Spiders', 'Edema', 'Bilirubin', 'Cholesterol', 'Albumin', 'Copper',
       'Alk_Phos', 'SGOT', 'Tryglicerides', 'Platelets', 'Prothrombin',
       'Stage'],
      dtype='object') Index(['N_Days', 'Status', 'Drug', 'Age', 'Sex', 'Ascites', 'Hepatomegaly',
       'Spiders', 'Edema', 'Bilirubin', 'Cholesterol', 'Albumin', 'Copper',
       'Alk_Phos', 'SGOT', 'Tryglicerides', 'Platelets', 'Prothrombin'],
      dtype='object')


In [65]:
print(df.shape)
df.isnull().sum()

(6800, 19)


N_Days              0
Status              0
Drug             2025
Age                 0
Sex                 0
Ascites          2246
Hepatomegaly     2427
Spiders          2590
Edema               0
Bilirubin           0
Cholesterol      3101
Albumin             0
Copper           2156
Alk_Phos         2498
SGOT             2102
Tryglicerides    2812
Platelets         338
Prothrombin       155
Stage               0
dtype: int64

In [66]:
categorical_cols=list(df.select_dtypes(include=('object')).columns)
continuous_cols=list(df.select_dtypes(include=(['int64', 'float64'])).columns)
continuous_cols.remove("Stage")
non_null_cols=list(df.columns[df.notnull().all()])
non_null_cols.remove("Stage")
print(categorical_cols,non_null_cols)
sorted_null_cols=['Prothrombin', 'Platelets', 'Drug', 'SGOT', 'Copper', 'Ascites', 'Hepatomegaly', 'Alk_Phos', 'Spiders', 'Tryglicerides', 'Cholesterol']

['Status', 'Drug', 'Sex', 'Ascites', 'Hepatomegaly', 'Spiders', 'Edema'] ['N_Days', 'Status', 'Age', 'Sex', 'Edema', 'Bilirubin', 'Albumin']


### Feature Encoding

In [67]:
 # replacing catagorical data with intigers in train data
df['Sex'] = df['Sex'].replace({'M':0, 'F':1})                                # Male : 0 , Female :1
df['Ascites'] = df['Ascites'].replace({'N':0, 'Y':1})                        # N : 0, Y : 1   
df['Drug'] = df['Drug'].replace({'D-penicillamine':0, 'Placebo':1})          # D-penicillamine : 0, Placebo : 1   
df['Hepatomegaly'] = df['Hepatomegaly'].replace({'N':0, 'Y':1})              # N : 0, Y : 1
df['Spiders'] = df['Spiders'].replace({'N':0, 'Y':1})                        # N : 0, Y : 1
df['Edema'] = df['Edema'].replace({'N':0, 'Y':1, 'S':-1})                    # N : 0, Y : 1, S : -1
df['Status'] = df['Status'].replace({'C':0, 'CL':1, 'D':-1})                 # 'C':0, 'CL':1, 'D':-1

 # replacing catagorical data with intigers in test data
df1['Sex'] = df1['Sex'].replace({'M':0, 'F':1})                                # Male : 0 , Female :1
df1['Ascites'] = df1['Ascites'].replace({'N':0, 'Y':1})                        # N : 0, Y : 1   
df1['Drug'] = df1['Drug'].replace({'D-penicillamine':0, 'Placebo':1})          # D-penicillamine : 0, Placebo : 1   
df1['Hepatomegaly'] = df1['Hepatomegaly'].replace({'N':0, 'Y':1})              # N : 0, Y : 1
df1['Spiders'] = df1['Spiders'].replace({'N':0, 'Y':1})                        # N : 0, Y : 1
df1['Edema'] = df1['Edema'].replace({'N':0, 'Y':1, 'S':-1})                    # N : 0, Y : 1, S : -1
df1['Status'] = df1['Status'].replace({'C':0, 'CL':1, 'D':-1})   

### Handling Missing Values

In [68]:
df.isnull().sum()

N_Days              0
Status              0
Drug             2025
Age                 0
Sex                 0
Ascites          2246
Hepatomegaly     2427
Spiders          2590
Edema               0
Bilirubin           0
Cholesterol      3101
Albumin             0
Copper           2156
Alk_Phos         2498
SGOT             2102
Tryglicerides    2812
Platelets         338
Prothrombin       155
Stage               0
dtype: int64

In [69]:
df.corr()

N_Days    Status      Drug       Age       Sex   Ascites  \
N_Days         1.000000  0.006840 -0.035978 -0.069048  0.013816 -0.031093   
Status         0.006840  1.000000 -0.013506 -0.001128  0.001164  0.008727   
Drug          -0.035978 -0.013506  1.000000  0.022108 -0.024106  0.009293   
Age           -0.069048 -0.001128  0.022108  1.000000 -0.014149 -0.010194   
Sex            0.013816  0.001164 -0.024106 -0.014149  1.000000  0.008337   
Ascites       -0.031093  0.008727  0.009293 -0.010194  0.008337  1.000000   
Hepatomegaly   0.016119 -0.012336  0.010275  0.007326  0.025391  0.004788   
Spiders        0.033535 -0.020520 -0.015001 -0.029718  0.025404  0.016540   
Edema          0.013727  0.005777  0.005933  0.006170  0.000761  0.001361   
Bilirubin      0.013037 -0.010623  0.005009  0.017183 -0.006151 -0.004251   
Cholesterol    0.045464  0.045075 -0.006536 -0.035271 -0.004399  0.011066   
Albumin       -0.028400  0.001007 -0.015917 -0.011826  0.010137 -0.004148   
Copper         0.008272  0.006169  0.016241 -0.043328 -0.016111  0.002621   
Alk_Phos      -0.011724  0.023031  0.036587  0.014469  0.020542 -0.003345   
SGOT          -0.022703  0.022049  0.051108  0.036427 -0.014293  0.004006   
Tryglicerides  0.099012  0.034721  0.022982  0.032096 -0.010295  0.001957   
Platelets      0.042913  0.003505  0.027758  0.105258 -0.000127 -0.018179   
Prothrombin   -0.006062  0.001908 -0.000772  0.005112  0.006570 -0.007914   
Stage          0.004066  0.026065  0.000584 -0.001854 -0.012433 -0.016884   

               Hepatomegaly   Spiders     Edema  Bilirubin  Cholesterol  \
N_Days             0.016119  0.033535  0.013727   0.013037     0.045464   
Status            -0.012336 -0.020520  0.005777  -0.010623     0.045075   
Drug               0.010275 -0.015001  0.005933   0.005009    -0.006536   
Age                0.007326 -0.029718  0.006170   0.017183    -0.035271   
Sex                0.025391  0.025404  0.000761  -0.006151    -0.004399   
Ascites            0.004788  0.016540  0.001361  -0.004251     0.011066   
Hepatomegaly       1.000000  0.016257  0.010037   0.000823     0.044094   
Spiders            0.016257  1.000000 -0.006925   0.021225    -0.009384   
Edema              0.010037 -0.006925  1.000000   0.001000    -0.019649   
Bilirubin          0.000823  0.021225  0.001000   1.000000     0.005986   
Cholesterol        0.044094 -0.009384 -0.019649   0.005986     1.000000   
Albumin           -0.005921  0.004038  0.005843   0.062583     0.023670   
Copper            -0.018030  0.003506 -0.016123   0.001208    -0.013332   
Alk_Phos           0.017047 -0.010428 -0.003993   0.040346    -0.031814   
SGOT              -0.007079  0.024053  0.001269   0.020157     0.020435   
Tryglicerides      0.008365  0.000085  0.015509  -0.009782     0.046358   
Platelets         -0.020649 -0.013254 -0.014821  -0.037234    -0.017935   
Prothrombin       -0.022900 -0.028451 -0.003061  -0.019610    -0.012795   
Stage             -0.004158 -0.009396 -0.008758  -0.010225     0.033273   

                Albumin    Copper  Alk_Phos      SGOT  Tryglicerides  \
N_Days        -0.028400  0.008272 -0.011724 -0.022703       0.099012   
Status         0.001007  0.006169  0.023031  0.022049       0.034721   
Drug          -0.015917  0.016241  0.036587  0.051108       0.022982   
Age           -0.011826 -0.043328  0.014469  0.036427       0.032096   
Sex            0.010137 -0.016111  0.020542 -0.014293      -0.010295   
Ascites       -0.004148  0.002621 -0.003345  0.004006       0.001957   
Hepatomegaly  -0.005921 -0.018030  0.017047 -0.007079       0.008365   
Spiders        0.004038  0.003506 -0.010428  0.024053       0.000085   
Edema          0.005843 -0.016123 -0.003993  0.001269       0.015509   
Bilirubin      0.062583  0.001208  0.040346  0.020157      -0.009782   
Cholesterol    0.023670 -0.013332 -0.031814  0.020435       0.046358   
Albumin        1.000000  0.015370  0.001515 -0.039058      -0.001856   
Copper         0.015370  1.000000 -0.00

In [70]:
# a=df.isnull().sum().tolist()
# b=zip(a,list(df.columns))
# b=sorted(b)
# b=[element for _,element in b]
# print(list(df.columns),b)
sorted_null_cols=['Prothrombin', 'Platelets', 'Drug', 'SGOT', 'Copper', 'Ascites', 'Hepatomegaly', 'Alk_Phos', 'Spiders', 'Tryglicerides', 'Cholesterol']

In [71]:
df1.isnull().sum()

N_Days              0
Status              0
Drug              963
Age                 0
Sex                 0
Ascites          1087
Hepatomegaly     1102
Spiders          1200
Edema               0
Bilirubin           0
Cholesterol      1435
Albumin             0
Copper           1006
Alk_Phos         1168
SGOT              987
Tryglicerides    1286
Platelets         164
Prothrombin        64
dtype: int64

In [72]:
df_train=df.copy()
df_test=df1.copy()
to_drop_cols=['Drug', 'SGOT', 'Copper', 'Ascites', 'Hepatomegaly', 'Alk_Phos', 'Spiders', 'Tryglicerides', 'Cholesterol',"N_Days","Status"]
df_train=df_train.drop(to_drop_cols,axis=1)
df_test=df_test.drop(to_drop_cols,axis=1)

In [73]:
def custom_knn_imputer(df,df1,df2):
    from sklearn.neighbors import KNeighborsClassifier
    from sklearn.neighbors import KNeighborsRegressor
    i=1

    df_train_imputed=df.copy()
    df_test_imputed=df1.copy()
    df_val_imputed=df2.copy()
    for c in sorted_null_cols:

        df_train_train=df_train_imputed[df_train_imputed[c].notnull()]
        df_train_test=df_train_imputed[df_train_imputed[c].isnull()]
        train_X_train=df_train_train[non_null_cols]
        train_y_train=df_train_train.pop(c)
        train_X_test=df_train_test[non_null_cols]

        test_X=df_test_imputed[df_test_imputed[c].isnull()][non_null_cols]
        val_X=df_val_imputed[df_val_imputed[c].isnull()][non_null_cols]
        if c in continuous_cols:
            print(i,"co")
            knn=KNeighborsRegressor(n_neighbors=9)
            knn.fit(train_X_train,train_y_train)

            train_y_pred=knn.predict(train_X_test)
            df_train_imputed.loc[df_train_imputed[c].isnull(),c]=train_y_pred

            test_y_pred=knn.predict(test_X)
            df_test_imputed.loc[df_test_imputed[c].isnull(),c]=test_y_pred
            
            val_y_pred=knn.predict(val_X)
            df_val_imputed.loc[df_val_imputed[c].isnull(),c]=val_y_pred
        else:
            print(i,"ca")
            knn=KNeighborsClassifier(n_neighbors=9)
            knn.fit(train_X_train,train_y_train)

            train_y_pred=knn.predict(train_X_test)
            df_train_imputed.loc[df_train_imputed[c].isnull(),c]=train_y_pred

            test_y_pred=knn.predict(test_X)
            df_test_imputed.loc[df_test_imputed[c].isnull(),c]=test_y_pred
            
            val_y_pred=knn.predict(val_X)
            df_val_imputed.loc[df_val_imputed[c].isnull(),c]=val_y_pred
        non_null_cols.append(c)
        i+=1
    df_train_imputed.isnull().sum()
    return df_train_imputed,df_test_imputed,df_val_imputed

In [74]:
def custom_simple_imputer(df,df1,df2):
    for c in np.setdiff1d(continuous_cols,to_drop_cols):
        df[c].fillna(df[c].mean(), inplace=True)
        df1[c].fillna(df[c].mean(), inplace=True)
        df2[c].fillna(df[c].mean(), inplace=True)
    for c in np.setdiff1d(categorical_cols,to_drop_cols):
        df[c].fillna(df[c].mode().values[0], inplace=True)
        df1[c].fillna(df[c].mode().values[0], inplace=True)
        df2[c].fillna(df[c].mode().values[0], inplace=True)
    return df,df1,df2

In [76]:
def pre_process(X_train,X_test,X_val,imputer):

    df=X_train.copy()
    df1=X_test.copy()
    df2=X_val.copy()
    
    if imputer=="knn":
        custom_knn_imputer(df,df1,df2)
    elif imputer=="simple":
        custom_simple_imputer(df,df1,df2)
    
    from sklearn.preprocessing import StandardScaler
    scaler = StandardScaler()
    # df[continuous_cols] = scaler.fit_transform(df[continuous_cols]) #train dataset scaling
    # df1[continuous_cols] = scaler.transform(df1[continuous_cols]) #test dataset scaling
    cols=list(df.columns)
#     cols.remove("Stage")
#     print(cols)
    df[cols] = scaler.fit_transform(df[cols]) #train dataset scaling
#     df1[cols] = scaler.transform(df1[cols]) #test dataset scaling
#     df2[cols] = scaler.transform(df2[cols]) #test dataset scaling
    
    return df,df1,df2

In [77]:
X = df_train.drop(['Stage'], axis=1)
y = df_train.pop('Stage')

In [78]:
from sklearn import model_selection
from sklearn.metrics import f1_score

skf=model_selection.StratifiedKFold(n_splits=5,shuffle=True,random_state=42)
preds=[]
val_score=[]
for fold, (train_indices, valid_indices) in enumerate(skf.split(X,y)):
    
    X_train=X.iloc[train_indices]
    y_train=y.iloc[train_indices]
    X_val=X.iloc[valid_indices]
    y_val=y.iloc[valid_indices]
    X_test=df_test.copy()

    X_train,X_test,X_val=pre_process(X_train,X_test,X_val,"simple")

    from xgboost import XGBClassifier
    model = XGBClassifier(n_learning_rate=0.75, max_depth=3,eval_metric='auc',n_estimators=150 ,random_state=fold, gamma=0,verbose=10000)
    model.fit(X_train, y_train,early_stopping_rounds=50,eval_set=[(X_val,y_val)])

    preds_val = model.predict(X_val)
    score=f1_score(y_val,preds_val,average ="weighted")
    val_score.append(score)
    print(fold,score)

    preds_test=model.predict_proba(X_test)
    preds.append(preds_test)
fscore=np.mean(np.array(val_score))

[23:15:58] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.0/src/learner.cc:576: 
Parameters: { "n_learning_rate", "verbose" } might not be used.

  This could be a false alarm, with some parameters getting used by language bindings but
  then being mistakenly passed down to XGBoost core, or some parameter actually being used
  but getting flagged wrongly here. Please open an issue if you find any such cases.


[0]	validation_0-auc:0.50000
[1]	validation_0-auc:0.50272
[2]	validation_0-auc:0.50553
[3]	validation_0-auc:0.51080
[4]	validation_0-auc:0.51587
[5]	validation_0-auc:0.52175
[6]	validation_0-auc:0.51299
[7]	validation_0-auc:0.51422
[8]	validation_0-auc:0.51024
[9]	validation_0-auc:0.50681
[10]	validation_0-auc:0.50640
[11]	validation_0-auc:0.50365
[12]	validation_0-auc:0.49978
[13]	validation_0-auc:0.49636
[14]	validation_0-auc:0.49625
[15]	validation_0-auc:0.49719
[16]	validation_0-auc:0.50330
[17]	validation_0-auc:0.50860
[18]	validation_0-auc:0.50739
[19]	

[51]	validation_0-auc:0.49700
[52]	validation_0-auc:0.49699
[53]	validation_0-auc:0.49561
[54]	validation_0-auc:0.49545
[55]	validation_0-auc:0.49694
[56]	validation_0-auc:0.49675
[57]	validation_0-auc:0.49753
[58]	validation_0-auc:0.49787
[59]	validation_0-auc:0.49913
[60]	validation_0-auc:0.49910
[61]	validation_0-auc:0.49916
[62]	validation_0-auc:0.49902
[63]	validation_0-auc:0.49857
[64]	validation_0-auc:0.49785
[65]	validation_0-auc:0.49856
[66]	validation_0-auc:0.49827
[67]	validation_0-auc:0.49816
[68]	validation_0-auc:0.49845
[69]	validation_0-auc:0.49895
[70]	validation_0-auc:0.49873
[71]	validation_0-auc:0.49873
[72]	validation_0-auc:0.49841
[73]	validation_0-auc:0.49897
[74]	validation_0-auc:0.49894
[75]	validation_0-auc:0.49925
[76]	validation_0-auc:0.49935
[77]	validation_0-auc:0.49934
[78]	validation_0-auc:0.49932
[79]	validation_0-auc:0.49929
[80]	validation_0-auc:0.49964
[81]	validation_0-auc:0.49967
[82]	validation_0-auc:0.50004
[83]	validation_0-auc:0.50013
[84]	valid

In [83]:
print(fscore)

0.36025119121543014


In [79]:
p=np.mean(preds,axis=0)

In [80]:
print(p)

[[0.15006268 0.18850127 0.27098897 0.39044708]
 [0.14580293 0.18723398 0.2486262  0.41833687]
 [0.1462265  0.1857442  0.26778668 0.40024263]
 ...
 [0.15029821 0.19054571 0.30083296 0.35832316]
 [0.15782717 0.21507688 0.3261164  0.30097955]
 [0.1457203  0.18576738 0.26798788 0.40052444]]


In [81]:
p_=np.argmax(p,axis=1)
p_=p_+1

In [82]:
res=pd.DataFrame(p_)
res.index = df_test.index # its important for comparison. Here "test_new" is your new test dataset
res.columns = ["Stage"]
res.to_csv("prediction_results102.csv", index = False) 

### submission successful

In [85]:
#some models I tried based on unbalaced nature of data but did give good results

In [86]:
def simple_model1():
    from xgboost import XGBClassifier
    
    model = XGBClassifier(learning_rate=0.75, max_depth=3, random_state=42, gamma=0, eval_metric='error')
    model.fit(X_train, y_train)
    predictions = model.predict(X_test)
    res = pd.DataFrame(predictions) #preditcions are nothing but the final predictions of your model on input features of your new unseen test data
    res.index = df_test.index # its important for comparison. Here "test_new" is your new test dataset
    res.columns = ["Stage"]
    res.to_csv("prediction_results101.csv", index = False) 

In [87]:
def simple_model2():
    from xgboost import XGBClassifier
    from sklearn.utils import class_weight
    classes_weights = class_weight.compute_sample_weight(
        class_weight='balanced',
        y=y_train
    )

    model = XGBClassifier(learning_rate=0.75, max_depth=3, random_state=1, gamma=0, eval_metric='error')
    model.fit(X_train, y_train,sample_weight=classes_weights)
    predictions = model.predict(X_test)
    res = pd.DataFrame(predictions) #preditcions are nothing but the final predictions of your model on input features of your new unseen test data
    res.index = df_test.index # its important for comparison. Here "test_new" is your new test dataset
    res.columns = ["Stage"]
    res.to_csv("prediction_results101.csv", index = False) 

In [88]:
def simple_model3():
    from xgboost import XGBClassifier
    from imblearn.ensemble import BalancedBaggingClassifier

    model=BalancedBaggingClassifier(base_estimator=XGBClassifier(learning_rate=0.75, max_depth=3, random_state=1, gamma=0, eval_metric='error'),
                                sampling_strategy='not majority',
                                replacement=False,
                                random_state=42)
    model.fit(X_train, y_train)
    predictions = model.predict(X_test)
    res = pd.DataFrame(predictions) #preditcions are nothing but the final predictions of your model on input features of your new unseen test data
    res.index = df_test.index # its important for comparison. Here "test_new" is your new test dataset
    res.columns = ["Stage"]
    res.to_csv("prediction_results101.csv", index = False) 

In [89]:
def simple_model4():
    from xgboost import XGBClassifier
    
    weights = y_train.value_counts()/len(df)
    
    model = XGBClassifier(learning_rate=0.75, max_depth=3, random_state=1, gamma=0, eval_metric='error',class_weight=weights)
    model.fit(X_train, y_train)
    predictions = model.predict(X_test)
    res = pd.DataFrame(predictions) #preditcions are nothing but the final predictions of your model on input features of your new unseen test data
    res.index = df_test.index # its important for comparison. Here "test_new" is your new test dataset
    res.columns = ["Stage"]
    res.to_csv("prediction_results101.csv", index = False) 

In [27]:
def simple_model5(X_train,y_train,X_test):
    from imblearn.over_sampling import SMOTE
    oversample = SMOTE()
    X_train, y_train = oversample.fit_resample(X_train, y_train)
    
    from xgboost import XGBClassifier
    
    model = XGBClassifier(learning_rate=0.75, max_depth=3, random_state=1, gamma=0, eval_metric='error')
    model.fit(X_train, y_train)
    predictions = model.predict(X_test)
    res = pd.DataFrame(predictions) #preditcions are nothing but the final predictions of your model on input features of your new unseen test data
    res.index = df_test.index # its important for comparison. Here "test_new" is your new test dataset
    res.columns = ["Stage"]
    res.to_csv("prediction_results101.csv", index = False) 